[package]
name = "elura-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
readme = "../../README.md"
description = "Project scaffold generator for Elura applications"
documentation = "https://docs.rs/elura-cli"

[dependencies]
elura-core.workspace = true

[[bin]]
name = "elura"
path = "src/main.rs"
doc = false
