[package]
name = "elura-realtime-gameplay-example"
version = "0.2.11"
edition = "2024"
publish = false

[workspace]
resolver = "3"

[dependencies]
elura = { path = "../../crates/elura", default-features = false, features = [
    "room",
    "aoi",
    "simulation",
    "netcode",
    "replication",
    "lag-compensation",
    "net-sim",
] }
