[package]
name = "elura-load"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Connection and request load generator for Elura Gateways"
publish = false

[dependencies]
bytes.workspace = true
futures-util.workspace = true
elura-core.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
