apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elura
resources:
  - namespace.yaml
  - discovery-config.yaml
  - gateway.yaml
  - world.yaml
  - network-policy.yaml

# Replace this with the upper project's image containing its business modules.
images:
  - name: elura-game
    newName: elura-game
    newTag: dev
