[package]
name = "elura-perf"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
elura-adapters = { version = "0.1.1", path = "../../crates/elura-adapters", default-features = false, features = ["redis"] }
elura-core.workspace = true
elura-gateway.workspace = true
elura-runtime.workspace = true
elura-world.workspace = true
tokio.workspace = true

[[bin]]
name = "elura-perf-gateway"
path = "src/bin/gateway.rs"

[[bin]]
name = "elura-perf-world"
path = "src/bin/world.rs"
