services:
  load-balancer:
    ports:
      - "${ELURA_PERF_BIND_ADDRESS:-0.0.0.0}:${ELURA_PERF_PORT:-17000}:17000"
      - "${ELURA_PERF_BIND_ADDRESS:-0.0.0.0}:${ELURA_PERF_WEBSOCKET_PORT:-17002}:17002"
  gateway-1:
    ports:
      - "${ELURA_PERF_BIND_ADDRESS:-0.0.0.0}:${ELURA_PERF_QUIC_PORT:-17003}:17003/udp"
      - "${ELURA_PERF_BIND_ADDRESS:-0.0.0.0}:${ELURA_PERF_UDP_PORT:-17004}:17004/udp"
      - "${ELURA_PERF_BIND_ADDRESS:-0.0.0.0}:${ELURA_PERF_WEBTRANSPORT_PORT:-17005}:17005/udp"
